baseURL = "https://mvpete.github.io/aspektproject.org/"
languageCode = "en-us"
title = "[ASPeKT] Project"
theme = "aspekt" 
pygmentsUseClasses = "true"
pygmentsStyle = "solarized-dark256"
publishDir = "docs"